// <auto-generated />
namespace MangoInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class MangoInventoryV59 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MangoInventoryV59));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200134381_MangoInventoryV59"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
