// <auto-generated />
namespace MangoInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class MangoInventoryV66 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MangoInventoryV66));
        
        string IMigrationMetadata.Id
        {
            get { return "201707011221152_MangoInventoryV66"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
